name: HipHop News Aggregator 2025
on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:  # Allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Run Scraper
        run: |
          node hiphop-agent.js
          date >> runs.log
          
      - name: Commit Results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add articles.json runs.log
          git commit -m "Update articles $(date)"
          git push